import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'
import Bodylist from '@/components/bodylist'
import Section from '@/components/section'
import Bodylist2 from '@/components/bodylist2'
import Section2 from '@/components/section2'
import Section3 from '@/components/section3'
import Section4 from '@/components/section4'
import Section5 from '@/components/section5'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {children}
        {/* <Bodylist /> */}
        <Bodylist2/>
        <Section/>
        <Section2/>
        <Section3/>
        <Section4/>
        <Section5/>
        </body>
    </html>
  )
}
